# Generated by Django 5.0.7 on 2024-08-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MhiLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_txt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mhi_language',
            },
        ),
        migrations.CreateModel(
            name='MhiLuAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_code_txt', models.TextField(blank=True, null=True)),
                ('assignment_desc_txt', models.TextField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mhi_lu_assignment',
            },
        ),
        migrations.CreateModel(
            name='MhiLuRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code_txt', models.TextField(blank=True, null=True)),
                ('role_desc_txt', models.TextField(blank=True, null=True)),
                ('role_level_num', models.IntegerField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mhi_lu_role',
            },
        ),
        migrations.CreateModel(
            name='MhiPerson',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.TextField(blank=True, null=True)),
                ('name_full_txt', models.TextField(blank=True, null=True)),
                ('name_first_txt', models.TextField(blank=True, null=True)),
                ('name_last_txt', models.TextField(blank=True, null=True)),
                ('type_txt', models.TextField(blank=True, null=True)),
                ('status_txt', models.TextField(blank=True, null=True)),
                ('portal_number_txt', models.TextField(blank=True, null=True)),
                ('phone_num', models.TextField(blank=True, null=True)),
                ('email_txt', models.TextField(blank=True, null=True)),
                ('address_txt', models.TextField(blank=True, null=True)),
                ('address_street_txt', models.TextField(blank=True, null=True)),
                ('address_city_txt', models.TextField(blank=True, null=True)),
                ('address_state_txt', models.TextField(blank=True, null=True)),
                ('address_zip_code_txt', models.TextField(blank=True, null=True)),
                ('home_ward_txt', models.TextField(blank=True, null=True)),
                ('home_stake_txt', models.TextField(blank=True, null=True)),
                ('assignment', models.TextField(blank=True, db_column='Assignment', null=True)),
                ('role', models.TextField(blank=True, db_column='Role', null=True)),
                ('assigned_area_txt', models.TextField(blank=True, null=True)),
                ('assigned_ward_txt', models.TextField(blank=True, null=True)),
                ('note_txt', models.TextField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mhi_person',
            },
        ),
        migrations.CreateModel(
            name='MhiAssignmentRole',
            fields=[
                ('assignment_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
                ('ar_report_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiassignmentrole')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiluassignment')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhilurole')),
            ],
            options={
                'db_table': 'mhi_assignment_role',
            },
        ),
        migrations.CreateModel(
            name='MhiAreaWard',
            fields=[
                ('area_ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_nm', models.TextField(blank=True, null=True)),
                ('ward_nm', models.TextField(blank=True, null=True)),
                ('community_nm', models.TextField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiperson')),
            ],
            options={
                'db_table': 'mhi_area_ward',
            },
        ),
        migrations.CreateModel(
            name='MhiPersonAssignmentRole',
            fields=[
                ('person_assignment_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_role_seq', models.IntegerField(blank=True, null=True)),
                ('assignment_dt', models.TextField(blank=True, null=True)),
                ('assignment_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiassignmentrole')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiperson')),
            ],
            options={
                'db_table': 'mhi_person_assignment_role',
            },
        ),
        migrations.CreateModel(
            name='MhiPersonContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_type_txt', models.TextField(blank=True, null=True)),
                ('contact_purpose_txt', models.TextField(blank=True, null=True)),
                ('contact_notes_txt', models.TextField(blank=True, null=True)),
                ('last_edit_dt', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiperson')),
            ],
            options={
                'db_table': 'mhi_person_contact',
            },
        ),
        migrations.CreateModel(
            name='MhiPersonLanguage',
            fields=[
                ('person_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_seq', models.IntegerField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhilanguage')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiperson')),
            ],
            options={
                'db_table': 'mhi_person_language',
            },
        ),
        migrations.CreateModel(
            name='MhiProcessTracking',
            fields=[
                ('process_track_id', models.AutoField(primary_key=True, serialize=False)),
                ('missionary_portal_number_txt', models.TextField(blank=True, null=True)),
                ('bishop_nm', models.TextField(blank=True, null=True)),
                ('bishop_phone', models.TextField(blank=True, null=True)),
                ('bishop_email', models.BinaryField(blank=True, null=True)),
                ('stake_pres_nm', models.FloatField(blank=True, null=True)),
                ('stake_pres_phone', models.BinaryField(blank=True, null=True)),
                ('stake_pres_email', models.TextField(blank=True, null=True)),
                ('call_volunteer_dt', models.DateField(blank=True, null=True)),
                ('call_volunteer_letter_dt', models.DateField(blank=True, null=True)),
                ('release_dt', models.DateField(blank=True, null=True)),
                ('badge_ordered_yn', models.CharField(blank=True, db_column='badge_ordered_YN', max_length=1, null=True)),
                ('badge_received_yn', models.CharField(blank=True, db_column='badge_received_YN', max_length=1, null=True)),
                ('badge_received_dt', models.DateField(blank=True, null=True)),
                ('missionary_portal_complete_dt', models.DateField(blank=True, null=True)),
                ('last_edit_dt', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mhiperson')),
            ],
            options={
                'db_table': 'mhi_process_tracking',
            },
        ),
    ]
